wsgiserver: implement parse_headers
adafruit/Adafruit_CircuitPython_ESP32SPI pull request #115
Opened 2020-11-12 17:14 UTC by Anton-2

This PR implements parse_headers, which is not available in adafruit_requests anymore.

It also adds a default return status of 500 Internal Server Error, this helped me when debugging an app using Adafruit_CircuitPython_WSGI.

Lastly, we always add a Connection: close header. The server is not ready to handle keep-alive requests, it seems better to make it clear for the client.

2020-11-16 19:31 UTC, astrilchuk commented
Thanks @Anton-2 for this fix.  I hope it gets merged soon since the wsgiserver is currently broken.

2020-12-14 18:43 UTC, siddacious requested changes
@Anton-2 Apologies for the delay; `parse_headers` exists in request as `_parse_headers` a private-ish method of the class, WSGIServer needs to be updated to not try to parse the headers itself and instead access the parsed headers with `Response.headers`.

2021-06-01 19:39 UTC, jposada202020 commented
@Anton-2 this is a long time (I know) are you still interested on working on this, if so, could you take intro consideration the comments above.  let us know thanks :)

2021-06-03 09:17 UTC, Neradoc commented
`wsgiserver` does not make requests, it only uses the `parse_headers` function to pass them to the application. I might be missing something, but I don't see how or why we would want to use the `Response` class here instead of just duplicating the function from the old requests (and drop the dependency) like the PR does.

2021-06-04 18:26 UTC, jposada202020 commented
@brentru Hello :) what are your thoughts on this?
Thanks

2021-06-04 18:44 UTC, brentru commented
The proposed changes make sense to me.

2021-06-04 18:49 UTC, jposada202020 commented
Good Thanks, if that is the case I think this is settled, I will let some day to merge to see after bumping this PR other folks have comments. Thanks

2021-06-06 22:59 UTC, merged